<?xml version="1.0"?>
<robot name="cartpole_balancer" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name = "base_length" value = "0.6"/>
    <xacro:property name = "base_width" value = "0.4"/>
    <xacro:property name = "base_height" value = "0.2"/>
    <xacro:property name = "wheel_length" value = "0.1"/>
    <xacro:property name = "wheel_radius" value = "0.05"/>
    <xacro:property name = "cartpole_length" value = "0.4"/>
    <xacro:property name = "cartpole_radius" value = "0.005"/>
    <xacro:property name = "bob_radius" value = "0.02"/>
    <xacro:property name = "base_mass" value = "5"/>
    <xacro:property name = "wheel_mass" value = "1"/>
    <xacro:property name = "cartpole_mass" value = "0.1"/>
    <xacro:property name = "bob_mass" value = "0.5"/>

    <link name="root_link"/>
    <joint name="root_base_joint" type="fixed">
        <parent link="root_link"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.15" rpy="0.0 0.0 0.0"/>
    </joint>
    

    <link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${base_mass}"/>
            <inertia ixx="${(base_mass)/12*(base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0" iyy="${(base_mass)/12*(base_length*base_length + base_height*base_height)}" iyz="0.0" izz="${(base_mass)/12*(base_length*base_length + base_width*base_width)}"/>
        </inertial>
        <visual name="visual">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="material">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
    </link>

    <xacro:macro name="wheels_links" params="name">
        <link name="${name}_link">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${(wheel_mass/12)*(3*wheel_radius*wheel_radius + wheel_length*wheel_length)}" ixy="0.0" ixz="0.0" iyy="${(wheel_mass/12)*(3*wheel_radius*wheel_radius + wheel_length*wheel_length)}" iyz="0.0" izz="${(wheel_mass/2)*(wheel_radius*wheel_radius)}"/>
            </inertial>
            <visual name="visual_2">
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="material">
                    <color rgba="0.0 0.0 1.0 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2.0} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="wheel_joints" params="name x y">
        <joint name="${name}_joint" type="continuous">
            <origin xyz="${x*(base_length / 4.0)} ${y*(base_width) / 2.0} -${base_height / 2.0}" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${name}_link"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>
    </xacro:macro>

    <xacro:wheels_links name = "front_left_wheel"/>
    <xacro:wheels_links name = "front_right_wheel"/>
    <xacro:wheels_links name = "rear_left_wheel"/>
    <xacro:wheels_links name = "rear_right_wheel"/>

    <xacro:wheel_joints name = "front_left_wheel" x = "1.0" y = "1.0"/>
    <xacro:wheel_joints name = "front_right_wheel" x = "1.0" y = "-1.0"/>
    <xacro:wheel_joints name = "rear_left_wheel" x = "-1.0" y = "1.0"/>
    <xacro:wheel_joints name = "rear_right_wheel" x = "-1.0" y = "-1.0"/>

    <link name="cartpole_link">
        <inertial>
            <origin xyz="0.0 0.0 0.2" rpy="0.0 0.0 0.0"/>
            <mass value="${cartpole_mass}"/>
            <inertia ixx="${(cartpole_mass/12)*(3*cartpole_radius*cartpole_radius + cartpole_length*cartpole_length)}" ixy="0.0" ixz="0.0" iyy="${(cartpole_mass/12)*(3*cartpole_radius*cartpole_radius + cartpole_length*cartpole_length)}" iyz="0.0" izz="${(cartpole_mass/2)*(cartpole_radius*cartpole_radius)}"/>
        </inertial>
        <visual name="visual">
            <origin xyz="0.0 0.0 0.2" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${cartpole_radius}" length="${cartpole_length}"/>
            </geometry>
            <material name = "zzzzz">
                <color rgba="0.0 0.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.2" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${cartpole_radius}" length="${cartpole_length}"/>
            </geometry>
        </collision>
    </link>

    <joint name="cartpole_base_joint" type="revolute">
        <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="cartpole_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="-0.7" upper="0.7" effort="0.0" velocity="0.0"/>
    </joint>

    <link name="bob_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${bob_mass}"/>
            <inertia ixx="${((2*bob_mass)/5)*(bob_radius*bob_radius)}" ixy="0.0" ixz="0.0" iyy="${((2*bob_mass)/5)*(bob_radius*bob_radius)}" iyz="0.0" izz="${((2*bob_mass)/5)*(bob_radius*bob_radius)}"/>
        </inertial>
        <visual name="visual">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${bob_radius}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 1.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${bob_radius}"/>
            </geometry>
        </collision>
    </link>
    <joint name="bob_cartpole_joint" type="fixed">
        <parent link="cartpole_link"/>
        <child link="bob_link"/>
        <origin xyz="0.0 0.0 0.4" rpy="0.0 0.0 0.0"/>
    </joint>

    
    

</robot>
